<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-HHODFUV" name="tests.FaceboolLogins" tests="6" failures="1" timestamp="02 Sep 2021 19:12:22 GMT" time="269.818" errors="0">
  <testcase name="loginWithWrong_1" time="82.488" classname="tests.FaceboolLogins"/>
  <testcase name="loginWithNoEmail_2" time="79.229" classname="tests.FaceboolLogins"/>
  <testcase name="loginWithNoPass_3" time="9.959" classname="tests.FaceboolLogins"/>
  <testcase name="loginWithInvalidEmail_4" time="10.161" classname="tests.FaceboolLogins"/>
  <testcase name="wrongNumber_5" time="8.929" classname="tests.FaceboolLogins"/>
  <testcase name="emailNoAccount_6" time="79.052" classname="tests.FaceboolLogins">
    <failure type="org.junit.ComparisonFailure" message="expected:&lt;...ected to an account.[]&gt; but was:&lt;...ected to an account.[ Find your account and log in.]&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<...ected to an account.[]> but was:<...ected to an account.[ Find your account and log in.]>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at tests.FaceboolLogins.emailNoAccount_6(FaceboolLogins.java:77)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.TestNG.privateMain(TestNG.java:1354)
at org.testng.TestNG.main(TestNG.java:1323)
]]>
    </failure>
  </testcase> <!-- emailNoAccount_6 -->
</testsuite> <!-- tests.FaceboolLogins -->
